# Generated by Django 5.1.4 on 2026-05-28 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel (MB51)'), ('SAP_PROCUREMENT', 'SAP Procurement (ME2N)'), ('UTILITY_ELECTRICITY', 'Utility Electricity (Green Button CSV)'), ('TRAVEL', 'Corporate Travel (Concur Export)')], max_length=30)),
                ('original_filename', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('parsed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestions', to='accounts.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel_air', 'Business Travel — Air'), ('business_travel_hotel', 'Business Travel — Hotel'), ('business_travel_ground', 'Business Travel — Ground'), ('purchased_goods', 'Purchased Goods & Services')], max_length=40)),
                ('activity_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=20)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=20)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('emission_factor_source', models.CharField(max_length=100)),
                ('source_plant_code', models.CharField(blank=True, max_length=50)),
                ('source_meter_id', models.CharField(blank=True, max_length=100)),
                ('source_record_id', models.CharField(blank=True, max_length=100)),
                ('source_vendor', models.CharField(blank=True, max_length=255)),
                ('source_material', models.CharField(blank=True, max_length=255)),
                ('raw_source_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('flags', models.JSONField(default=dict)),
                ('flag_reasons', models.JSONField(default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='accounts.company')),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.dataingestion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('INGESTED', 'Ingested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('EDITED', 'Edited'), ('LOCKED', 'Locked')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.emissionrecord')),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
    ]
